---
title: "Pocillopora meta-transcriptome SNP analysis"
author: "Mike Connelly"
date: "02/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Setup packages and working directories
```{r}
library("vcfR")
library("tidyverse")
library("adegenet")
library("ggrepel")
#
library("extrafont")
library("extrafontdb")
```
## Import sample metadata
```{r factor levels}
study_levels <- c("Mayfield2014", "Vidal-Dupiol2014", "Yuan2017", "Zhou2017", "Brener-Raffali2018", "Delgadillo-Nuno2018", "Tang2018", "Wecker2018", "Zhou2018", "Poquita-Du2019", "Zhou2019", "Buitrago-Lopez2020", "Chuang-Mitarai2020", "Li2020", "ConnellyEAPSI", "Grupstra2022")
```
```{r}
# Import sample metadata 
samples <- read_csv("data/SampleData_MetaPocillopora_012722.csv") %>% 
  dplyr::filter(Include_SNPs == TRUE) %>% 
  dplyr::mutate("Sample_ID" = str_c(`Study`, `Sample`, sep = "_"))
# 
```

```{r}
#pdam_genome <- ape::read.dna("/Users/mikeconnelly/computing/sequences/genomes/coral/pocillopora/pdam/pdam_genome.fasta", format = "fasta")
```
```{r}
#pdam_gff <- read.table("/Users/mikeconnelly/computing/sequences/genomes/coral/pocillopora/pdam/pdam_genome.gff", sep="\t", quote="")
```
```{r colors}
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
gcolors <- gg_color_hue(n_distinct(samples$Study))
```

## Import VCF file
```{r imporf vcf}
# vcf_meta <- vcfR::read.vcfR(file = "./outputs/phylotrans_pdam/metapocillopora_004_filtered_strict.vcf")
vcf_meta <- vcfR::read.vcfR(file = "./outputs/phylotrans_pdam/filtered_vcfs/max-missing-0.75_indv-missing-0.75_max-missing_0.1.recode.vcf")
```

## Convert to GENIND object
```{r genind convert}
genind_meta <- vcfR2genind(vcf_meta)
# class(genind_meta)
genind_meta
```
```{r genind summary}
# genind_summary_meta <- summary(genind_meta)
```

## PCA
```{r pca}
# 
x_meta <- tab(genind_meta, freq = TRUE, NA.method = "mean")
# 
pca_meta <- dudi.pca(x_meta, center = TRUE, scale = FALSE, scannf = FALSE, nf = 216)
# ?dudi.pca()
```
```{r pca plot check}
s.label(pca_meta$li, xax=2, yax=3)
```

## Figure 5
```{r}
pca_df <- pca_meta$li %>%
  rownames_to_column("Sample_ID") %>%
  dplyr::mutate(Sample_ID = str_replace(`Sample_ID`, "_1$", "")) %>% 
  right_join(samples, by = "Sample_ID")
pca_df$Study <- factor(pca_df$Study, levels = study_levels, ordered = TRUE)
```
```{r PC_vars}
pc1lab <- paste("PC1: ", round(pca_meta$eig[1]/sum(pca_meta$eig)*100, 2), "%", sep = "")
pc2lab <- paste("PC2: ", round(pca_meta$eig[2]/sum(pca_meta$eig)*100, 2), "%", sep = "")
```
```{r}
# Figure 5 
pca_title <- expression(paste("PCA of phylotranscriptomic SNPs (7,688)"))
pdf("./outputs/figures/Fig5_VCF_SNPs_pca_all_0.75_Q20.pdf", height = 7.5, width = 9)
pca_df %>%
  ggplot(., aes(Axis1, Axis2)) +
  geom_point( aes(fill = Study, shape = Species), size = 6, alpha = 0.8, stroke = 0.5, color = "black") + 
  # stat_ellipse(aes(color = Species), show.legend = FALSE) +
  # geom_text_repel(aes(label = Sample_ID), size = 2, max.overlaps = 100)
  scale_fill_manual(values = gg_color_hue(n_distinct(samples$Study)),
                    guide = guide_legend(override.aes = list(size = 6, shape = 21, fill = gg_color_hue(n_distinct(samples$Study))),
                                         nrow = 8, title.position = "top")) +
  scale_shape_manual(values = c(21, 24, 22, 23),
                     guide = guide_legend(override.aes = list(size = 6, alpha = 0.8, stroke = 0.5, fill = "black"),
                                          nrow = 4, title.position = "top")) +
  # coord_fixed(10.04/16.78) + 
  theme_bw() +
  theme(plot.title = element_text(size = 28),
        axis.title = element_text(size = 24),
        axis.text = element_blank(),
        legend.title = element_text(size = 24),
        legend.text = element_text(size = 20),
        legend.position = "bottom",
        legend.spacing.y = unit(0.15, "in")) +
  xlab(pc1lab) + ylab(pc2lab) +
  ggtitle(pca_title)
dev.off()
```

## Find clusters in data
```{r}
# Find clusters
grp_meta <- find.clusters(genind_meta, max.n.clust = 100, n.pca = 300)
# All PCs retained, 37 clusters identified
```
```{r}
pdf("./outputs/adegenet/pca_find-clusters.pdf", height = 5, width = 6)
grp_meta <- find.clusters(genind_meta, max.n.clust = 40, n.pca = 41)
dev.off()
```
```{r}
# Inspect output of find.clusters
grp_meta$Kstat
grp_meta$stat
grp_meta$grp
grp_meta$size
```
## DAPC
```{r}
# Run the analysis on the dataset using the previously inferred groups
dapc_meta <- dapc(genind_meta, grp_meta$grp)
```
```{r}
# Inspect output of dapc
dapc_meta
dapc_meta$n.pca
dapc_meta$n.da
dapc_meta$tab
dapc_meta$var
```
```{r}
scatter(dapc_meta)
```
```{r}
pdf("./outputs/adegenet/dapc_all.pdf")
scatter(dapc_meta,
         scree.da=TRUE,  posi.da="bottomright",
         scree.pca=TRUE, posi.pca="bottomleft",
         bg="white", pch=20,  cell=0, cstar=0,
        cex=3,clab=0, leg=TRUE, txt.leg=paste("Cluster",1:37)) 
dev.off()
```
```{r}
scatter(dapc_meta, 1, 1, bg="white",
        scree.da=FALSE, legend=TRUE, solid=.4)
```
```{r}
scatter(dapc_meta, 2, 2, bg="white",
        scree.da=FALSE, legend=TRUE, solid=.4)
```

```{r}
# Add DAPC cluster group information to samples data frame
samples_grp <- data.frame("Sample_ID" = names(grp_meta$grp), "Group" = unname(grp_meta$grp)) %>% 
  dplyr::mutate(Sample_ID = str_replace(`Sample_ID`, "_1$", ""))
# 
samples_keep <- samples %>% 
  filter(Sample_ID %in% samples_grp$Sample_ID) %>% 
  left_join(samples_grp) %>% 
  arrange(Sample_ID)
# 
write_csv(samples_keep, "~/Desktop/samples_keep.csv")
write_csv(samples_grp, "~/Desktop/samples_grp.csv")
```
```{r}
samples_keep %>%
  group_by(Group) %>%
  dplyr::count() %>% 
  ggplot(aes(Group, n)) + geom_col()
  
samples_keep %>%
  ggplot(aes(Group)) +
  geom_bar(aes(fill = Genotype), color = "black") + #, position = "fill"
  facet_grid(Study ~ ., space = "free", switch = "y")
```


### DAPC variable contributions
```{r}
contrib <- loadingplot(dapc_meta$var.contr, axis=2,
                       thres=.07, lab.jitter=1)
# 
dapc_loadings <- data.frame(dapc_meta$var.contr) %>% 
  arrange(desc(LD1))
```

### Interpreting group memberships
```{r}
pdf("./outputs/figures_VCF_SNP_assignplot.pdf", width = 8.5, height = 11)
par(mar=c(4,10,4,4))
# summary(dapc_meta)
assignplot(dapc_meta)
dev.off()
```
```{r}
compoplot(dapc_meta, posi="bottomright",
          # txt.leg=paste("Cluster", 1:13), lab="",
          ncol=1, xlab="individuals", col=funky(6))
```

## Testing for Hardy-Weinberg equilibrium
```{r}

```

## Measuring and testing population structure (aka F statistics)
```{r}

```

## Estimating inbreeding
```{r}

```

## snapclust
```{r}
# adegenetTutorial("snapclust")
meta_clust <- snapclust(genind_meta, k = 16)
```
```{r}
meta_clust$group
# 
compoplot(meta_clust)
```

