---
title: "EAPSI_vcfR"
author: "Mike Connelly"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(vcfR)
library(SNPRelate)
library(phangorn)
library(poppr)
library(ape)
```
```{r}
colshapes <- c(16, 17, 15, 18)
colcolors <- c("olivedrab3", "springgreen", "deepskyblue", "skyblue")
theme_set(theme_bw())
```

vcfR section
```{r}
pdam_genome <- ape::read.dna("/Users/mikeconnelly/computing/sequences/genomes/coral/pocillopora/pdam/pdam_genome.fasta", format = "fasta")
```
```{r}
#pdam_gff <- read.table("/Users/mikeconnelly/computing/sequences/genomes/coral/pocillopora/pdam/pdam_genome.gff", sep="\t", quote="")
```
```{r}
vcf_Hw1a <- vcfR::read.vcfR(file = "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Hw1-6a.filtered.vcf.gz")
vcf_Hw2b <- vcfR::read.vcfR(file = "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Hw2-6b.filtered.vcf.gz")
vcf_Wt1a <- vcfR::read.vcfR(file = "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Wt1-6a.filtered.vcf.gz")
vcf_Wt2a <- vcfR::read.vcfR(file = "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Wt2-6a.filtered.vcf.gz")
```
```{r}
chrom <- create.chromR(name='Supercontig', vcf=vcf_Hw1a, seq=pdam_genome, ann=pdam_gff)
```

SNPrelate section
```{r}
Hw1a <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Hw1-6a.filtered.vcf"
Hw1b <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Hw1-6b.filtered.vcf"
Hw1c <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Hw1-6c.filtered.vcf"
Hw2b <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Hw2-6b.filtered.vcf"
Hw2c <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Hw2-6c.filtered.vcf"
Wt1a <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Wt1-6a.filtered.vcf"
Wt1b <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Wt1-6b.filtered.vcf"
Wt1c <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Wt1-6c.filtered.vcf"
Wt2a <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Wt2-6a.filtered.vcf"
Wt2b <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Wt2-6b.filtered.vcf"
Wt2c <- "/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/Wt2-6c.filtered.vcf"
```

```{r}
#snpgdsVCF2GDS() to read in each VCF
Hw1a_gds <- snpgdsVCF2GDS(Hw1a, "out_Hw1a", method = "biallelic.only")
Hw1b_gds <- snpgdsVCF2GDS(Hw1b, "out_Hw1b", method = "biallelic.only")
Hw1c_gds <- snpgdsVCF2GDS(Hw1c, "out_Hw1c", method = "biallelic.only")
Hw2b_gds <- snpgdsVCF2GDS(Hw2b, "out_Hw2b", method = "biallelic.only")
Hw2c_gds <- snpgdsVCF2GDS(Hw2c, "out_Hw2c", method = "biallelic.only")
Wt1a_gds <- snpgdsVCF2GDS(Wt1a, "out_Wt1a", method = "biallelic.only")
Wt1b_gds <- snpgdsVCF2GDS(Wt1b, "out_Wt1b", method = "biallelic.only")
Wt1c_gds <- snpgdsVCF2GDS(Wt1c, "out_Wt1c", method = "biallelic.only")
Wt2a_gds <- snpgdsVCF2GDS(Wt2a, "out_Wt2a", method = "biallelic.only")
Wt2b_gds <- snpgdsVCF2GDS(Wt2b, "out_Wt2b", method = "biallelic.only")
Wt2c_gds <- snpgdsVCF2GDS(Wt2c, "out_Wt2c", method = "biallelic.only")
```
```{r}
#then merge in R using snpgdsCombineGeno()
stable_gds <- snpgdsCombineGeno(gds.fn = c(Hw1a_gds, Hw1b_gds, Hw1c_gds, Hw2b_gds, Hw2c_gds, Wt1a_gds, Wt1b_gds, Wt1c_gds, Wt2a_gds, Wt2b_gds, Wt2c_gds), out.fn = "stable.gds", method = "position", verbose = TRUE)
```
```{r}
snpgdsSummary("/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/stable.gds")
```
```{r}
# Try different LD thresholds for sensitivity analysis
snpset <- snpgdsLDpruning(genofile, ld.threshold=0.2)
```
```{r}
# Run PCA
pca <- snpgdsPCA(genofile, snp.id=snpset.id, num.thread=2)
# variance proportion (%)
pc.percent <- pca$varprop*100
head(round(pc.percent, 2))
# make a data.frame
tab <- data.frame(sample.id = pca$sample.id,
    EV1 = pca$eigenvect[,1],    # the first eigenvector
    EV2 = pca$eigenvect[,2],    # the second eigenvector
    stringsAsFactors = FALSE)
head(tab)
# Draw
plot(tab$EV2, tab$EV1, xlab="eigenvector 2", ylab="eigenvector 1")
```
```{r}
# Get sample id
sample.id <- read.gdsn(index.gdsn(genofile, "sample.id"))

# Get population information
#   or pop_code <- scan("pop.txt", what=character())
#   if it is stored in a text file "pop.txt"
pop_code <- read.gdsn(index.gdsn(genofile, "sample.annot/pop.group"))

# assume the order of sample IDs is as the same as population codes
head(cbind(sample.id, pop_code))
# Make a data.frame
tab <- data.frame(sample.id = pca$sample.id,
    pop = factor(pop_code)[match(pca$sample.id, sample.id)],
    EV1 = pca$eigenvect[,1],    # the first eigenvector
    EV2 = pca$eigenvect[,2],    # the second eigenvector
    stringsAsFactors = FALSE)
head(tab)
```
```{r}
genofile <- snpgdsOpen("/Users/mikeconnelly/computing/scripts/EAPSI_HW-WT_v2-master/EAPSI-phylotrans/stable.gds")
```
```{r}
#pca
sample.id <- read.gdsn(index.gdsn(genofile, "sample.id"))
pop_code <- read.gdsn(index.gdsn(genofile, "sample.id"))
genotype <- gsub("-[0-9][abc]", "", pop_code)

pca <- snpgdsPCA(genofile)

tab <- data.frame(sample.id = pca$sample.id,
                  geno = factor(genotype)[match(pca$sample.id, sample.id)],
                  EV1 = pca$eigenvect[,1],
                  EV2 = pca$eigenvect[,2],
                  stringsAsFactors = FALSE)
```
```{r}
pdf("./EAPSI_SNP_PCA.pdf", width = 6, height = 4.5)
tab %>% ggplot(aes(EV1, EV2)) +
  geom_point(aes(shape = genotype, color = genotype), size = 6) + 
  scale_shape_manual(values = colshapes) + 
  scale_color_manual(values = colcolors)
```
```{r}
ibs.hc<-snpgdsHCluster(snpgdsIBS(genofile,num.thread=2, autosome.only=FALSE))
```
```{r}
rv <- snpgdsCutTree(ibs.hc)
```
```{r}
pdf("./EAPSI_SNP_tree.pdf", width = 6, height = 4.5)
plot(rv$dendrogram, main = "Taiwan Pocillopora SNP clustering tree")
```

```{r}
#LD based SNP pruning
set.seed(1000)
snpset <- snpgdsLDpruning(genofile, ld.threshold = 0.8)
snp.id <- unlist(snpset)

# distance matrix - use IBS
dissMatrix  =  snpgdsIBS(genofile,
                         sample.id=NULL,
                         snp.id=snp.id,
                         autosome.only=TRUE, 
    remove.monosnp=TRUE,  maf=NaN, missing.rate=NaN, num.thread=2, verbose=TRUE)
snpgdsClose(genofile)

snpHCluster =  snpgdsHCluster(dissMatrix, sample.id=NULL, need.mat=TRUE, hang=0.01)

cutTree = snpgdsCutTree(snpHCluster, z.threshold=15, outlier.n=5, n.perm = 5000, samp.group=NULL, 
    col.outlier="red", col.list=NULL, pch.outlier=4, pch.list=NULL,label.H=FALSE, label.Z=TRUE, 
    verbose=TRUE)

snpgdsDrawTree(cutTree,
               main = "Taiwan Pocillopora SNP phylogenetic tree",
               edgePar=list(col=rgb(0.5,0.5,0.5,0.75), t.col="black"),y.label.kinship=T,leaflab="perpendicular")
```
