# /bin/sh 
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=64G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N bowtie_build_symABCD
#$ -o bowtie_build_symABCD.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/bowtie2
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
bowtie2-build \
/scratch/nmnh_corals/connellym/sequences/symbio/symABCDgenome.fasta \
/scratch/nmnh_corals/connellym/sequences/symbiosymABCDgenome \
--threads $NSLOTS
#
#
echo = `date` job $JOB_NAME done
