# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=4G,h_data=4G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N fastqdump_Yuan2017
#$ -o fastqdump_Yuan2017
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/sratoolkit
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
#
mkdir ${prodir}/data/srareads/Li2020
#
SRAaccessions=$(cat ${prodir}/data/SRR_Acc_List_Yuan2017.txt)
for SRA in "$SRAaccessions"
do \
fastq-dump --split-files --outdir ${prodir}/data/srareads/Yuan2017 --gzip $SRA
done
#
echo = `date` job $JOB_NAME done
