# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -q sThC.q
#$ -l mres=4G,h_data=4G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N fastqdump_test
#$ -o fastqdump_test.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/sratoolkit
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
#
SRRnums=$(cat ${prodir}/data/SraAccList_PRJNA327142.txt)
#
for SRRnum in $SRRnums
do \
echo "This is the SRA file being downloaded and converted to .fastq format $SRRnum"
#
fastq-dump --split-files --outdir ${prodir}/data/srareads/ --gzip ${SRRnum}
#
echo "$SRRnum acquired and converted to .fastq format"
#
echo = `date` job $JOB_NAME done
