# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 16
#$ -q sThC.q
#$ -l mres=32G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N featureCounts_ConnellyEAPSI
#$ -o featureCounts_ConnellyEAPSI.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
study="$1"
#
/home/connellym/programs/subread-2.0.3-source/bin/featureCounts \
-T $NSLOTS \
-t gene \
-g ID \
-a /home/connellym/sequences/pdam_annotation.gff3 \
-o ${prodir}/outputs/featureCounts_pdam/ConnellyEAPSI_Pdam.counts \
${prodir}/outputs/STARalign_pdam/ConnellyEAPSI/*Aligned.out.bam
#
echo = `date` job $JOB_NAME done
