#!/bin/bash

prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
study="$1"
files=$(ls $prodir/data/srareads/$study)
samples=$(echo "$files" | cut -d _ -f 1,2 | sort -u)

for sample in $samples
do
echo "# /bin/sh" > $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
echo "# ----------------Parameters---------------------- #" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
echo "#$  -S /bin/sh
#$ -pe mthread 16
#$ -q sThC.q
#$ -l mres=64G,h_data=4G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N gatk_HC_${sample}
#$ -o ${prodir}/bash/jobs/gatk_haplotypecaller_${sample}.log
#$ -m bea
#$ -M connellym@si.edu" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
#
echo "# ----------------Modules------------------------- #" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
echo "module load bioinformatics/gatk" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
#
echo "# ----------------Your Commands------------------- #" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
echo 'echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME' >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
echo 'echo + NSLOTS = $NSLOTS' >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
echo "#" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
#
echo 'echo "This is the sample being processed:"' >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
echo "echo $sample" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
#
echo 'echo "Starting GATK HaplotypeCaller steps"' >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
echo "#" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
#
echo "java -jar /share/apps/bioinformatics/gatk/3.8.1.0/GenomeAnalysisTK.jar \
-T HaplotypeCaller \
-I ${prodir}/outputs/phylotrans_pdam/${study}/${sample}_pdam_Aligned.sorted.out.md.rg.splitN.bam \
-o ${prodir}/outputs/phylotrans_pdam/${study}/${sample}_pdam.g.vcf.gz \
-R /home/connellym/sequences/pdam_scaffolds.fasta \
-stand_call_conf 20.0 \
-dontUseSoftClippedBases" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
echo "#" >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
#
echo 'echo = `date` job $JOB_NAME done' >> $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
#qsub $prodir/bash/jobs/gatk_haplotypecaller_${sample}.job
done
