# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 8
#$ -q mThC.q
#$ -l mres=64G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N gatk_genotype_gvcfs_final_samples_both
#$ -o gatk_genotype_gvcfs_final_samples_both.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/gatk
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
java -jar /share/apps/bioinformatics/gatk/3.8.1.0/GenomeAnalysisTK.jar \
-T GenotypeGVCFs \
-R /home/connellym/sequences/pdam_scaffolds.fasta \
-V ${prodir}/outputs/phylotrans_pdam/metapocillopora_final_samples_both.g.vcf.gz \
-o ${prodir}/outputs/phylotrans_pdam/metapocillopora_final_samples_both.vcf.gz
#
echo = `date` job $JOB_NAME done
