# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 8
#$ -q mThC.q
#$ -l mres=64G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N gatk_combine_gvcfs_select
#$ -o gatk_combine_gvcfs_select.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/gatk
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
java -jar /share/apps/bioinformatics/gatk/3.8.1.0/GenomeAnalysisTK.jar \
-T CombineGVCFs \
-R /home/connellym/sequences/pdam_scaffolds.fasta \
--variant ${prodir}/outputs/phylotrans_pdam/Vidal-Dupiol2014/Vidal-Dupiol2014_SRR988670_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Vidal-Dupiol2014/Vidal-Dupiol2014_SRR988671_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Vidal-Dupiol2014/Vidal-Dupiol2014_SRR988672_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727374_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727379_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727380_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Wecker2018/Wecker2018_SRR5215316_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Wecker2018/Wecker2018_SRR5215317_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Wecker2018/Wecker2018_SRR5215318_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Wecker2018/Wecker2018_SRR5215319_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2018/Zhou2018_SRR6001268_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2018/Zhou2018_SRR6001269_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2018/Zhou2018_SRR6001270_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Poquita-Du2019/Poquita-Du2019_SRR6914908_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Poquita-Du2019/Poquita-Du2019_SRR6934388_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Poquita-Du2019/Poquita-Du2019_SRR6934542_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Poquita-Du2019/Poquita-Du2019_SRR6951423_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Poquita-Du2019/Poquita-Du2019_SRR6951744_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Poquita-Du2019/Poquita-Du2019_SRR6952431_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Poquita-Du2019/Poquita-Du2019_SRR7042978_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Poquita-Du2019/Poquita-Du2019_SRR7043013_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Poquita-Du2019/Poquita-Du2019_SRR7043704_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2019/Zhou2019_SRR6784730_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2019/Zhou2019_SRR6784731_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2019/Zhou2019_SRR6784732_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2019/Zhou2019_SRR6784733_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2019/Zhou2019_SRR6784734_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2019/Zhou2019_SRR6784735_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395133_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395134_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395135_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395151_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395152_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395154_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395170_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395171_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395172_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395189_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395190_1_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/ConnellyEAPSI/ConnellyEAPSI_SRR10395191_1_pdam.g.vcf.gz \
--out ${prodir}/outputs/phylotrans_pdam/metapocillopora_003.g.vcf.gz
#
echo = `date` job $JOB_NAME done
