# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 8
#$ -q mThC.q
#$ -l mres=64G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N gatk_combine_gvcfs_test
#$ -o gatk_combine_gvcfs_test.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/gatk
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
java -jar /share/apps/bioinformatics/gatk/3.8.1.0/GenomeAnalysisTK.jar \
-T CombineGVCFs \
-R /home/connellym/sequences/pdam_scaffolds.fasta \
-nct 8 \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2018/Zhou2018_SRR6001268_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2018/Zhou2018_SRR6001269_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2018/Zhou2018_SRR6001270_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2018/Zhou2018_SRR6001271_pdam.g.vcf.gz \
--variant ${prodir}/outputs/phylotrans_pdam/Zhou2018/Zhou2018_SRR6001273_pdam.g.vcf.gz \
--out ${prodir}/outputs/phylotrans_pdam/metapocillopora_001.g.vcf.gz
#
echo = `date` job $JOB_NAME done
#--variant ${prodir}/outputs/phylotrans_pdam/Zhou2018/Zhou2018_SRR6001272_pdam.g.vcf.gz \
