# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 16
#$ -q sThC.q
#$ -l mres=32G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N phylotrans_process_Zhou2017_single_test
#$ -o phylotrans_process_Zhou2017_single_test.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/picard-tools
module load bioinformatics/samtools
module load bioinformatics/gatk
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
files=$(ls $prodir/data/srareads/Zhou2017)
samples=$(echo "$files" | cut -d . -f 1)
#
# test for single Zhou2017 sample: Zhou2017_SRR3727281
samtools sort \
${prodir}/outputs/STARalign_pdam/Zhou2017/Zhou2017_SRR3727281_pdam_Aligned.out.bam \
> ${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_pdam_Aligned.sorted.out.bam
#
samtools index -b \
${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_pdam_Aligned.sorted.out.bam
#
java -jar /share/apps/bioinformatics/picard-tools/2.20.6/picard.jar \
AddOrReplaceReadGroups \
INPUT=${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_pdam_Aligned.sorted.out.bam \
OUTPUT=${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_pdam_Aligned.sorted.out.rg.bam \
RGID=id \
RGLB=library \
RGPL=illumina \
RGPU=unit1 \
RGSM=Zhou2017_SRR3727281
#
java -jar /share/apps/bioinformatics/picard-tools/2.20.6/picard.jar \
MarkDuplicates \
INPUT=${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_pdam_Aligned.sorted.out.rg.bam \
OUTPUT=${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_pdam_Aligned.sorted.out.md.rg.bam \
CREATE_INDEX=true \
VALIDATION_STRINGENCY=SILENT \
METRICS_FILE=${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_marked_dup_metrics.txt
#
java -jar /share/apps/bioinformatics/gatk/3.8.1.0/GenomeAnalysisTK.jar \
-T SplitNCigarReads \
-I ${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_pdam_Aligned.sorted.out.md.rg.bam \
-o ${prodir}/outputs/phylotrans_pdam/Zhou2017/Zhou2017_SRR3727281_pdam_Aligned.sorted.out.md.rg.splitN.bam \
-R /home/connellym/sequences/pdam_scaffolds.fasta \
-rf ReassignOneMappingQuality \
-RMQF 255 -RMQT 60 \
-U ALLOW_N_CIGAR_READS
#
echo = `date` job $JOB_NAME done
