# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 20
#$ -q sThC.q
#$ -l mres=160G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N raxmlHPC_meta_006
#$ -o raxmlHPC_meta_006.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/raxml
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
#
raxmlHPC \
-f a \
-m GTRGAMMA \
-x 123476 \
-# 1000 \
-T $NSLOTS \
-p 12345 \
-s ${prodir}/outputs/nexus-phylips/vcf_meta_0.95_unlinked.vcf.min0.phy \
-w ${prodir}/outputs/raxml/raxml_run_006/ \
-n vcf_meta_0.95_unlinked
#
echo = `date` job $JOB_NAME done
# test
