#!/bin/bash

prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
study="$1"
files=$(ls $prodir/data/srareads/$study)
samples=$(echo "$files" | cut -d _ -f 1,2 | sort -u)
#
for sample in $samples
do
echo "# /bin/sh" > $prodir/bash/jobs/staralign_mt_${sample}.job
echo "# ----------------Parameters---------------------- #" >> $prodir/bash/jobs/staralign_mt_${sample}.job
echo "#$  -S /bin/sh
#$ -pe mthread 16
#$ -q sThC.q
#$ -l mres=64G,h_data=4G,h_vmem=4G" >> $prodir/bash/jobs/staralign_mt_${sample}.job
echo "#$ -j y
#$ -N staralign_${sample}
#$ -o ${prodir}/bash/jobs/staralign_mt_${sample}.log
#$ -m bea
#$ -M connellym@si.edu" >> $prodir/bash/jobs/staralign_mt_${sample}.job
#
echo "# ----------------Modules------------------------- #" >> $prodir/bash/jobs/staralign_mt_${sample}.job
#
echo "# ----------------Your Commands------------------- #" >> $prodir/bash/jobs/staralign_mt_${sample}.job
#
echo 'echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME' >> $prodir/bash/jobs/staralign_mt_${sample}.job
echo 'echo + NSLOTS = $NSLOTS' >> $prodir/bash/jobs/staralign_mt_${sample}.job
#
# Align trimmed reads against reference genome using STAR
echo "/home/connellym/programs/STAR-2.7.9a/bin/Linux_x86_64/STAR \
--runMode alignReads \
--quantMode TranscriptomeSAM \
--runThreadN 16 \
--readFilesIn /scratch/nmnh_corals/connellym/projects/MetaPocillopora/outputs/trimmedreads/${study}/${sample}_1P_trimmed.fastq.gz \
/scratch/nmnh_corals/connellym/projects/MetaPocillopora/outputs/trimmedreads/${study}/${sample}_2P_trimmed.fastq.gz \
--readFilesCommand gunzip -c \
--genomeDir /home/connellym/sequences/STARidx_pdam_mt \
--sjdbGTFfeatureExon exon \
--sjdbGTFtagExonParentTranscript Parent \
--sjdbGTFfile  /home/connellym/sequences/pdam_mt_ncbi.gff3 \
--twopassMode Basic \
--twopass1readsN -1 \
--outStd Log BAM_Unsorted \
--outSAMtype BAM Unsorted \
--outFileNamePrefix ${prodir}/outputs/STARalign_pdam/${study}/mitochondria/${sample}_pdam_" >> $prodir/bash/jobs/staralign_mt_${sample}.job
#
echo 'echo = `date` job $JOB_NAME done' >> $prodir/bash/jobs/staralign_mt_${sample}.job
qsub $prodir/bash/jobs/staralign_mt_${sample}.job
done
