# /bin/sh 
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -q sThC.q
#$ -l mres=4G,h_data=4G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N starbuild_mt
#$ -o starbuild_mt.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
/home/connellym/programs/STAR-2.7.9a/bin/Linux_x86_64/STAR \
--runMode genomeGenerate \
--genomeDir /home/connellym/sequences/STARidx_pdam_mt \
--genomeFastaFiles /home/connellym/sequences/pdam_mt.fasta \
--genomeSAindexNbases 6 \
--sjdbGTFtagExonParentTranscript Parent \
--sjdbGTFfile /home/connellym/sequences/pdam_mt_ncbi.gff3 \
--sjdbOverhang 49
#
echo = `date` job $JOB_NAME done
