# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 16
#$ -q sThC.q
#$ -l mres=16G,h_data=1G,h_vmem=1G
#$ -cwd
#$ -j y
#$ -N trimqc_Zhou2019
#$ -o trimqc_Zhou2019.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/fastqc
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
fastqc \
/scratch/nmnh_corals/connellym/projects/MetaPocillopora/outputs/trimmedreads/Zhou2019/* \
--threads $NSLOTS \
-o /scratch/nmnh_corals/connellym/projects/MetaPocillopora/outputs/QCs/trimqcs/
#
echo = `date` job $JOB_NAME done
