# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -pe mthread 16
#$ -q sThC.q
#$ -l mres=64G,h_data=4G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N trimmomatic_single_test_Zhou2017
#$ -o trimmomatic_single_test_Zhou2017.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/trimmomatic
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
# Trim adapter sequences and poor-quality bases using Trimmomatic
java -jar /share/apps/bioinformatics/trimmomatic/0.39/trimmomatic-0.39.jar \
SE \
-phred33 \
-trimlog /scratch/nmnh_corals/connellym/projects/MetaPocillopora/outputs/trimlogs/Zhou2017_SRR3727424_trim.log \
/scratch/nmnh_corals/connellym/projects/MetaPocillopora/data/srareads/Zhou2017/Zhou2017_SRR3727424.fastq.gz \
/scratch/nmnh_corals/connellym/projects/MetaPocillopora/outputs/trimmedreads/Zhou2017/Zhou2017_SRR3727424_trimmed.fastq.gz \
ILLUMINACLIP:/share/apps/bioinformatics/trimmomatic/0.39/adapters/TruSeq3-SE.fa:2:30:10 \
LEADING:3 \
TRAILING:3 \
SLIDINGWINDOW:4:15 \
MINLEN:36
#
echo = `date` job $JOB_NAME done
