#!/bin/bash

prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
files=$(ls $prodir/data/srareads/Zhou2017)
samples=$(echo "$files" | cut -d . -f 1)
#
for sample in $samples
do
echo "# /bin/sh" > $prodir/bash/jobs/trimmomatic_${sample}.job
echo '# ----------------Parameters---------------------- #' >> $prodir/bash/jobs/trimmomatic_${sample}.job
echo '#$  -S /bin/sh
#$ -pe mthread 16
#$ -q sThC.q
#$ -l mres=64G,h_data=4G,h_vmem=4G' >> $prodir/bash/jobs/trimmomatic_${sample}.job
echo "'#$ -j y
#$ -N trimmomatic_{$sample}
#$ -o trimmomatic_{$sample}.log
#$ -m bea
#$ -M connellym@si.edu'" >> $prodir/bash/jobs/trimmomatic_${sample}.job
#
echo '# ----------------Modules------------------------- #'>> $prodir/bash/jobs/trimmomatic_${sample}.job
echo 'module load bioinformatics/trimmomatic' >> $prodir/bash/jobs/trimmomatic_${sample}.job
#
echo '# ----------------Your Commands------------------- #' >> $prodir/bash/jobs/trimmomatic_${sample}.job
#
echo "echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME" >> $prodir/bash/jobs/trimmomatic_${sample}.job
echo "echo + NSLOTS = $NSLOTS" >> $prodir/bash/jobs/trimmomatic_${sample}.job
#
# Trim adapter sequences and poor-quality bases using Trimmomatic
echo "java -jar /share/apps/bioinformatics/trimmomatic/0.39/trimmomatic-0.39.jar \
SE \
-phred33 \
-trimlog /scratch/nmnh_corals/connellym/projects/MetaPocillopora/outputs/trimlogs/{$sample}_trim.log \
/scratch/nmnh_corals/connellym/projects/MetaPocillopora/data/srareads/Zhou2017/{$sample}.fastq.gz \
/scratch/nmnh_corals/connellym/projects/MetaPocillopora/outputs/trimmedreads/Zhou2017/{$sample}_trimmed.fastq.gz \
ILLUMINACLIP:/share/apps/bioinformatics/trimmomatic/0.39/adapters/TruSeq3-SE.fa:2:30:10 \
LEADING:3 \
TRAILING:3 \
SLIDINGWINDOW:4:15 \
MINLEN:36" >> $prodir/bash/jobs/trimmomatic_${sample}.job
#
echo "echo = `date` job $JOB_NAME done'" >> $prodir/bash/jobs/trimmomatic_${sample}.job
#qsub $prodir/bash/jobs/trimmomatic_${sample}.job
done
