# /bin/sh
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -q sThC.q
#$ -l mres=4G,h_data=4G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N vcftools_filtering
#$ -o vcftools_filtering.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/vcflib
module load bioinformatics/vcftools
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
prodir="/scratch/nmnh_corals/connellym/projects/MetaPocillopora"
VCF_IN="${prodir}/outputs/phylotrans_pdam/metapocillopora_004.vcf.gz"
VCF_OUT="${prodir}/outputs/phylotrans_pdam/metapocillopora_004_filtered.vcf.gz"
MAF="0.01"
MISS="0.95"
QUAL="10"
MIN_DEPTH="10"
MAX_DEPTH="300"
vcftools --gzvcf $VCF_IN \
--remove-indels --maf $MAF --max-missing $MISS --minQ $QUAL \
--min-meanDP $MIN_DEPTH --max-meanDP $MAX_DEPTH \
--minDP $MIN_DEPTH --maxDP $MAX_DEPTH --recode --stdout | gzip -c > \
$VCF_OUT
#
echo = `date` job $JOB_NAME done
