#!/bin/bash
#BSUB -q general
#BSUB -J SRR3727281_gatkVF_pdam
#BSUB -o /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/logfiles/SRR3727281gatkVF_pdam%J.out
#BSUB -e /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/errorfiles/SRR3727281gatkVF_pdam%J.err
#BSUB -n 8
#BSUB -W 4:00
java -jar /share/apps/GATK/3.4.0/GenomeAnalysisTK.jar -T VariantFiltration -R /scratch/projects/transcriptomics/mikeconnelly/sequences/genomes/coral/pocillopora/pdam_genome.fasta -V /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/phylotrans_Pdam/SRR3727281.g.vcf.gz -window 35 -cluster 3 -filterName FS -filter "FS > 30.0" -filterName QD -filter "QD < 2.0" -o  /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/phylotrans_Pdam/SRR3727281.filtered.vcf.gz
echo Variant filtration of SRR3727281 complete
