#!/bin/bash
#BSUB -q bigmem
#BSUB -J SRR3727383_sradump
#BSUB -o /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/logfiles/SRR3727383sradump%J.out
#BSUB -e /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/errorfiles/SRR3727383sradump%J.err
#BSUB -n 8
#BSUB -W 4:00
echo This is the SRA file being downloaded and converted to .fastq format SRR3727383
/scratch/projects/transcriptomics/mikeconnelly/programs/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump --outdir /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/data/srareads/projectname/fastqs --gzip SRR3727383
echo SRR3727383 acquired and converted to .fastq format
