#!/bin/bash
#BSUB -q bigmem
#BSUB -J SRR8568563_sradump
#BSUB -o /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/logfiles/SRR8568563sradump%J.out
#BSUB -e /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/errorfiles/SRR8568563sradump%J.err
#BSUB -n 8
#BSUB -W 4:00
echo This is the SRA file being downloaded and converted to .fastq format SRR8568563
/scratch/projects/transcriptomics/mikeconnelly/programs/sratoolkit.2.9.0-ubuntu64/bin/fastq-dump --outdir /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/data/srareads/projectname/fastqs --gzip SRR8568563
echo SRR8568563 acquired and converted to .fastq format
