#!/bin/bash
#BSUB -q general
#BSUB -J SRR8568569_trimmomatic
#BSUB -o /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/logfiles/SRR8568569trim%J.out
#BSUB -e /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/errorfiles/SRR8568569trim%J.err
module load java/1.8.0_60
module load trimmomatic/0.36
echo Unzipping SRR8568569
gunzip /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/data/srareads/SRR8568569.fastq.gz
echo Trimming SRR8568569
/share/opt/java/jdk1.8.0_60/bin/java -jar /share/apps/trimmomatic/0.36/trimmomatic-0.36.jar \
SE \
-phred33 \
-trimlog /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/logfiles/SRR8568569_trim.log /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/data/srareads/SRR8568569.fastq /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/trimmomaticreads/SRR8568569_trimmed.fastq.gz ILLUMINACLIP:/scratch/projects/transcriptomics/mikeconnelly/programs/Trimmomatic-0.36/adapters/TruSeq3-SE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
echo SRR8568569 trimmed
gzip /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/data/srareads/SRR8568569.fastq
