#!/bin/bash
#BSUB -q bigmem
#BSUB -J SRR8568570_sradump
#BSUB -o /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/logfiles/SRR8568570sradump%J.out
#BSUB -e /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/outputs/errorfiles/SRR8568570sradump%J.err
#BSUB -n 8
#BSUB -W 4:00
This is the SRA file being downloaded and converted to .fastq format SRR8568570
/scratch/projects/transcriptomics/mikeconnelly/programs/sratoolkit.2.8.2-1-mac64/bin/fastq-dump --outdir /scratch/projects/transcriptomics/mikeconnelly/projects/MetaPocillopora/data/srareads/projectname/fastqs --gzip SRR8568570
echo SRR8568570 acquired and converted to .fastq format
